### ISSUE TITLE
no way for perfmon

### ISSUE THREAD

**Issue by Raven013** [zitryss/go-sample#1]
when use installation: 
```git clone https://github.com/zitryss/perfmon.git```
it requires my usrname and passwd.
and I can't find this project in your repo.  maybe it's time for a update?

**Comment by zitryss** [comment]
Hello, @Raven013!

The `perfmon` was updated and uploaded as `go-sample`. Use this one instead.

Regarding the username and password: it is absolutely normal when you use https. Try `git@github.com:zitryss/go-sample.git`.

Cheers!
Eugene
